### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by ff98sha** [lucashowardmiller/the_knowledge#4]
Got the following error when trying to run it:
[root@centos ~]# python the_knowledge.py
  File "the_knowledge.py", line 27
    return_url = f'{GOOGLE_PREFIX}{whitespace_to_plus(subject_search)}&{get_knowledge_panel(knowledge_panel_search)}&{KP_ONLY}'
                                           ^
SyntaxError: invalid syntax

**Comment by lucashowardmiller** [comment]
Are you using python 3.6 or greater, f strings are a fairly recent development. 

Irregardless, google appears to have fixed this issue on their end, so unfortunately this tool is fairly useless.
